### ISSUE TITLE
Private fields should not be included as named parameters in constructor

### ISSUE THREAD

**Issue by vladaman** [angel-dart/serialize#32]
When I use private fields in model class the generator generates constructors with unsupported named optional fields. This is also not mentioned in docs.

```
@serializable
abstract class _User extends Model {
  String _uuid;
}
```
generates:

```
class User extends _User {
  User(
      {this.id,
      this._uuid, // wrong
....
```

**Comment by thosakwe** [comment]
Have you tried placing an `@exclude` annotation on the private field?

This is mentioned in the documentation: https://github.com/angel-dart/serialize#excluding-keys

**Comment by thosakwe** [comment]
Secondly, if you're using private fields that shouldn't be present in the generated class, don't use an `abstract class` in this case.

**Comment by thosakwe** [comment]
As of version `2.0.10`, the generator will ignore any private field entirely, so not only will they never be serialized, but they will never appear in constructors.

I'll publish it in a few minutes, once the Travis build is complete.

**Comment by thosakwe** [comment]
https://pub.dartlang.org/packages/angel_serialize_generator/versions/2.0.10
