### ISSUE TITLE
Generated classes don't import models 

### ISSUE THREAD

**Issue by vladaman** [angel-dart/serialize#34]
When I generate classes with angel I get bunch of errors in the GUI and compile errors. The generated classes don't import base model. I guess that's expected but when I include import I get an error "_The part of directive must be the only directive in part_"

![screenshot from 2018-07-12 11-07-25](https://user-images.githubusercontent.com/907206/42623737-ea6cbf4c-85c3-11e8-81e7-e365adc58b7b.png)

![screenshot from 2018-07-12 11-09-00](https://user-images.githubusercontent.com/907206/42623770-fdfd22f4-85c3-11e8-918d-9a8ce689437a.png)

Also enums are not recognized such as:
![screenshot from 2018-07-12 11-09-55](https://user-images.githubusercontent.com/907206/42623815-1e9aff04-85c4-11e8-9ed0-e82ceafcaa1e.png)

![screenshot from 2018-07-12 11-23-06](https://user-images.githubusercontent.com/907206/42624583-fb10844e-85c5-11e8-898d-eb961dcf5b70.png)

**Comment by vladaman** [comment]
OK I found solution to this. You must include also in Model class:

```
part 'user_model.g.dart';
part 'user_model.serializer.g.dart'; // this was missing
```

**Comment by thosakwe** [comment]
Correct - this is the expected behavior; if the files aren’t generated as “part of,” then they’ll be unable to see your model class.
