### ISSUE TITLE
Provide example in documentation of code generation for source files that are not in the default folder

### ISSUE THREAD

**Issue by starlys** [angel-dart/serialize#54]
I'm not following how to run pub build and have it look in the non-default location

**Comment by thosakwe** [comment]
I’ve modified the build.yaml so that it wouldn’t impose defaults on project
structure, so it should “just work.”

There are targets in the build.yaml, *but* those should only apply to
angel_serialize_generator’s test files.

**Comment by starlys** [comment]
Without a build.yaml in my project, running "pub run build_runner build" in my project root folder does not find the source files that have classes marked with @serializable and does not create outputs, so I'm feeling like some documentation is missing. The readme only specifies that it looks in lib/src/models/**.dart. If I put a file there, it does find it. The answer might be obvious if you know the internals of build_runner, but the documentation on that is not so complete, so I'm really not sure of what the intended base functionality is. For now I can change the project structure to match the default behavior.

**Comment by thosakwe** [comment]
That section of the README is outdated - I must have forgotten to remove
that line at the time. I'll investigate the cause, though.
Not 100% sure why it's not working.

**Comment by thosakwe** [comment]
Updated the docs to reflect on this. Let me know if you continue to encounter the error in newer versions (I guess just reopen this).

In my attempts to reproduce this, I've been able to have files built in locations like `test/models/author.dart`, and `example/main.dart`.
